Repository pivotal-cf/docs-operating-pas, pull requests merged in 2020-03, with the labels that each got.

#19 Add details for improved Redirect URI configuration
  configure-multi-foundation.html.md.erb
Labels: scheduled

#20 Add details for improved Redirect URI configuration
  configure-multi-foundation.html.md.erb
Labels: in progress

#21 Add details for improved Redirect URI configuration
  configure-multi-foundation.html.md.erb
Labels: in progress

#22 Comma sign is added by mistake
  configure-multi-foundation.html.md.erb
Labels: unscheduled
