Repository pivotal-cf/docs-operating-pas, pull requests merged in 2021-01, with the labels that each got.

#44 Remove beta tag from AppUsageService endpoint
  accounting-report.html.md.erb
Labels: scheduled

#45 Clarification on storage requirements
  pas-vsphere-requirements.html.md.erb
Labels: unscheduled

#46 Update max-in-flight advice
  configuring.html.md.erb
Labels: in progress
